### ISSUE TITLE
We should include a PullRequest fragment in the underlying query

### ISSUE THREAD

**Issue by francisfuzz** [lee-dohm/close-matching-issues#356]
## Summary

Hello, @lee-dohm ! I'm using this GitHub Action for a project and the README tells me that it [can be used to close issues or pull requests](https://github.com/lee-dohm/close-matching-issues#use). I came across a case that attempted to close pull requests, but didn't. I've shared the steps to reproduce and a possible path forward below. 

Thanks for considering my feedback! 🙇 

### Steps to reproduce

At this time of writing, I noticed that this repository has a [number of open PRs](https://github.com/lee-dohm/close-matching-issues/pulls) from Dependabot tagged with `dependencies`. I chose these PRs to target [mocking this query](https://github.com/lee-dohm/close-matching-issues/blob/1ba65dc989e9ae63492e7a330958e2bccd2bf235/src/main.ts#L15-L25) using the [GitHub Docs' Explorer](https://docs.github.com/en/graphql/overview/explorer):

```graphql
query {
  search(first: 100, query: "repo:lee-dohm/close-matching-issues label:dependencies is:open", type:ISSUE) {
    nodes {
      ... on Issue {
        number
      }
    }
  }
}
```

I expected each pull request's number to be returned in the response, but instead get a bunch of empty objects:

<details>
<summary>Payload without numbers for PRs</summary>

```json
{
  "data": {
    "search": {
      "nodes": [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    }
  }
}
```
</details>

### Possible path forward

I double-checked the [`SearchType`](https://docs.github.com/en/graphql/reference/enums#searchtype) and see that there's no option for `PULL_REQUEST`, just `ISSUE`. I remembered that issues can either be "just issues" or pull requests, and re-ran the query to introduce a new `PullRequest` [fragment](https://graphql.org/learn/queries/#fragments):

```graphql
query {
  search(first: 100, query: "repo:lee-dohm/close-matching-issues label:dependencies is:open", type:ISSUE) {
    nodes {
      ... on Issue {
        number
      }
      ... on PullRequest {
        number
      }
    }
  }
}
```

<details>
<summary>Payload with numbers for PRs</summary>

```json
{
  "data": {
    "search": {
      "nodes": [
        {
          "number": 355
        },
        {
          "number": 351
        },
        {
          "number": 345
        },
        {
          "number": 333
        },
        {
          "number": 329
        },
        {
          "number": 308
        },
        {
          "number": 280
        },
        {
          "number": 273
        },
        {
          "number": 272
        },
        {
          "number": 271
        }
      ]
    }
  }
}
```

</details>

So it turns out that the `query.search` interface can return an `Issue` or a `PullRequest` depending on the results that are found. We can use the `__typename` meta field to inspect the underlying result:

```graphql
query {
  search(first: 100, query: "repo:lee-dohm/close-matching-issues label:dependencies is:open", type:ISSUE) {
    nodes {
      __typename #=> `PullRequest`
    }
  }
}
```

Here's a follow-up query that demonstrates how we can show the node's type name and its URL to illustrate the mix of both issues and pull requests returned:

```graphql
query {
  search(first: 10, query: "repo:lee-dohm/close-matching-issues", type: ISSUE) {
    nodes {
      __typename
      ... on Issue {
        url
      }
      ... on PullRequest {
        url
      }
    }
  }
}
```

I'd like to cut a PR for this, if that's alright! 😎

**Comment by francisfuzz** [comment]
Leaving this for me:

- [ ] Update [`test/main.test.ts`](https://github.com/lee-dohm/close-matching-issues/blob/main/test/main.test.ts) with desired behavior for fetching a list of pull requests
- [ ] Update [`src/main.ts`](https://github.com/lee-dohm/close-matching-issues/blob/main/src/main.ts) with the `PullRequest` fragment

**Comment by lee-dohm** [comment]
@francisfuzz Thanks for this detailed writeup and solution. A PR for this would be great! Thank you so much, as always 🙇‍♂️
